version: '3'

services:
  open-trade-gateway:
    image: opentradegateway
    volumes:
      - ./docker/conf:/etc/open-trade-gateway
      - ./docker/user:/var/local/lib/open-trade-gateway
      - ./docker/log:/var/log/open-trade-gateway
    ports:
      - "7788:7788"
    expose:
      - "7788"
    entrypoint:
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          open-trade-gateway

